### ISSUE TITLE
Black Screen after loading [Experimental Fix]

### ISSUE THREAD

**Issue by FuzzyPixelGameStudio** [skymen/animate-text#3]
When I launch my project - it stops loading after construct 3 logo, leaving black screen.

Attached the console screenshot. I've found out that the "Experimental Fix" is the issue. An empty project with Animate Text startsbut stops at black screen if I add Experimental Fix to it.

Experimental fix still works fine at Construct r350 stable release, but I can't update any higher now.

![expfixbug](https://github.com/skymen/animate-text/assets/147412069/6d567aab-f4a6-4e6f-9d41-e88e021d580a)

**Comment by skymen** [comment]
Fixed
https://www.construct.net/en/make-games/addons/906/experimental-text-fix/versions
https://github.com/skymen/experimental-text-fix
